language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
#  - 7.2
#  - 7.3

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise

cache:
  directories:
    - $HOME/.composer

install:
  - composer install --prefer-dist

script:
  - php vendor/bin/phpunit

#after_success:
#  - travis_retry php vendor/bin/php-coveralls
